### ISSUE TITLE
Hello, questions and use

### ISSUE THREAD

**Issue by figuerres** [TeamworkGuy2/ts-simplog#1]
i have been using an old package of the log4javascript  for a while.
i was looking at updates and see this port to typescript.
1)  is this going to be updated ?
2) does the Ajax Appender work ?

currently i used the old ajax appender to log client messages to a remote server.
sometimes it fails to work.
my app is angular 2/4  so i use typescript and an idea is that in an angular service HTTP call the catch error is not getting the initialized code.

**Comment by TeamworkGuy2** [comment]
Thanks for your interest!  Unfortunately I probably won't have time in the near future to do any work on this.  I removed or rewrote large portions the original log4javascript code.  Some of the public API and most of the internals have been modified. 
This library is currently meeting my needs in another project (which uses the local storage and console appends and doesn't require the Ajax Appender) so I'm unlikely to be maintaining this in future beyond minor patches. 
Pull requests are always welcome or feel free to fork this if you feel like digging into the code.

**Comment by figuerres** [comment]
just as a comment it is amazing how many folks have copied some of the code from log4javascript and none of them have made a full port. i have other things to work on also so i have to see what i will do.
